# Translation Settings
target_lang: "Chinese"
ollama_model: "translategemma:12b"
temperature: 0.1
max_parallel_files: 2

# Path Settings
input_dir: "./docs"
output_dir: "./translated_docs"
cache_name_foramt: ".{}_cache.json"

# Hasher Settings
hash_algo: "SHA1"

translate_file_types:
  - ".md"
  - ".mdx"
  - ".txt"